const cfg=window.DZD_SUPABASE;
const SESSION_KEY='dzd-admin-session';
let session=null, products=[];
const $=id=>document.getElementById(id);
const money=n=>Number(n).toLocaleString('ar-DZ')+' دج';
function msg(text){$('loginMsg').textContent=text;$('loginMsg').classList.remove('hidden')}
function headers(){return {'apikey':cfg.key,'Authorization':`Bearer ${session.access_token}`,'Content-Type':'application/json'}}
async function auth(email,password){const r=await fetch(`${cfg.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:cfg.key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||'بيانات الدخول غير صحيحة');return d}
async function rpc(name){const r=await fetch(`${cfg.url}/rest/v1/rpc/${name}`,{method:'POST',headers:headers(),body:'{}'});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||'تعذر تنفيذ العملية');return d}
async function checkAdmin(){return !!(await rpc('is_admin'))}
async function login(){try{msg('جارٍ تسجيل الدخول...');session=await auth($('email').value.trim(),$('password').value);localStorage.setItem(SESSION_KEY,JSON.stringify(session));if(!(await checkAdmin())){localStorage.removeItem(SESSION_KEY);session=null;throw new Error('هذا الحساب ليس مديراً بعد. سجّل الدخول ثم اضغط تفعيل هذا الحساب كأول مدير إذا كان هذا أول حساب إدارة.')}$('loginBox').classList.add('hidden');$('panel').classList.remove('hidden');await loadAll()}catch(e){msg(e.message)}}
async function claim(){try{if(!session)session=await auth($('email').value.trim(),$('password').value);const ok=await rpc('claim_first_admin');if(!ok)throw new Error('يوجد مدير مفعّل مسبقاً. استخدم حساب المدير.');localStorage.setItem(SESSION_KEY,JSON.stringify(session));$('loginBox').classList.add('hidden');$('panel').classList.remove('hidden');await loadAll()}catch(e){msg(e.message)}}
function logout(){localStorage.removeItem(SESSION_KEY);session=null;location.reload()}
async function api(path,opts={}){const r=await fetch(`${cfg.url}/rest/v1/${path}`,{...opts,headers:{...headers(),...(opts.headers||{})}});if(!r.ok){let d={};try{d=await r.json()}catch{};throw new Error(d.message||d.hint||'فشل الطلب')}return r.status===204?null:r.json()}
async function loadProducts(){products=await api('products?select=id,name,description,price_dzd,category,icon,file_key,file_name,download_limit,active,created_at&order=id');$('statProducts').textContent=products.length;renderProducts()}
async function loadOrders(){const rows=await api('orders?select=id,order_code,customer_name,customer_email,customer_phone,payment_method,status,total_dzd,payment_reference,paid_at,created_at&order=created_at.desc');$('statOrders').textContent=rows.length;$('ordersList').innerHTML=rows.length?rows.map(o=>`<div class="order"><div class="order-head"><strong>${o.order_code}</strong><span class="status ${o.status}">${o.status}</span></div><div>${o.customer_name} · ${o.customer_phone} · ${o.customer_email}</div><div class="muted">${new Date(o.created_at).toLocaleString('ar-DZ')} · ${money(o.total_dzd)}</div></div>`).join(''):'<div class="empty">لا توجد طلبات بعد.</div>'}
function renderProducts(){$('productList').innerHTML=products.length?products.map(p=>`<div class="admin-row"><div><strong>${p.icon} ${escapeHtml(p.name)}</strong><div class="muted">${money(p.price_dzd)} · ${escapeHtml(p.category)} · ${p.active?'ظاهر':'مخفي'}</div></div><div class="actions"><button onclick="editProduct(${p.id})">تعديل</button><button class="danger" onclick="removeProduct(${p.id})">حذف</button></div></div>`).join(''):'<div class="empty">لا توجد منتجات.</div>'}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$('editId').value=p.id;$('name').value=p.name;$('desc').value=p.description;$('price').value=p.price_dzd;$('cat').value=p.category;$('icon').value=p.icon;$('fileKey').value=p.file_key||'';$('fileName').value=p.file_name||'';$('downloadLimit').value=p.download_limit||5;$('active').checked=!!p.active;$('formTitle').textContent='تعديل المنتج';window.scrollTo({top:0,behavior:'smooth'})}
async function saveProduct(e){e.preventDefault();try{const id=$('editId').value;const body={name:$('name').value.trim(),description:$('desc').value.trim(),price_dzd:Number($('price').value),category:$('cat').value,icon:($('icon').value||'📦').trim(),file_key:$('fileKey').value.trim()||null,file_name:$('fileName').value.trim()||null,download_limit:Number($('downloadLimit').value)||5,active:$('active').checked,updated_at:new Date().toISOString()};if(!body.name||!body.description||!Number.isFinite(body.price_dzd)||body.price_dzd<=0)throw new Error('أدخل اسم ووصف وسعر صحيح.');if(id)await api(`products?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});else{const max=products.reduce((m,p)=>Math.max(m,Number(p.id)),0);body.id=max+1;await api('products',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)})}resetForm();await loadProducts()}catch(e){alert(e.message)}}
async function removeProduct(id){if(!confirm('هل تريد حذف هذا المنتج من قاعدة البيانات؟'))return;try{await api(`products?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'});await loadProducts()}catch(e){alert(e.message)}}
function resetForm(){$('productForm').reset();$('editId').value='';$('icon').value='📦';$('downloadLimit').value=5;$('active').checked=true;$('formTitle').textContent='إضافة منتج'}
async function loadAll(){await Promise.all([loadProducts(),loadOrders()])}
$('loginBtn').onclick=login;$('claimBtn').onclick=claim;$('logoutBtn').onclick=logout;$('productForm').onsubmit=saveProduct;$('cancelEdit').onclick=resetForm;
(async()=>{try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');if(session?.access_token&&await checkAdmin()){$('loginBox').classList.add('hidden');$('panel').classList.remove('hidden');await loadAll()}}catch{localStorage.removeItem(SESSION_KEY);session=null}})();