const cfg=window.DZD_SUPABASE;
const SESSION_KEY='dzd-admin-session';
const BUCKET='products-private';
let session=null, products=[];
const $=id=>document.getElementById(id);
const money=n=>Number(n).toLocaleString('ar-DZ')+' دج';
function msg(text){$('loginMsg').textContent=text;$('loginMsg').classList.remove('hidden')}
function saveSession(){if(session?.access_token)localStorage.setItem(SESSION_KEY,JSON.stringify(session))}
function loadStoredSession(){try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{session=null}}
async function refreshSession(){if(!session?.refresh_token)return false;const r=await fetch(`${cfg.url}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:cfg.key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});if(!r.ok){localStorage.removeItem(SESSION_KEY);session=null;return false}session=await r.json();saveSession();return !!session?.access_token}
async function ensureSession(){if(session?.access_token)return true;loadStoredSession();if(session?.access_token)return true;return await refreshSession()}
function headers(json=true){if(!session?.access_token)throw new Error('انتهت جلسة الإدارة. سجّل الدخول من جديد.');const h={apikey:cfg.key,Authorization:`Bearer ${session.access_token}`};if(json)h['Content-Type']='application/json';return h}
async function auth(email,password){const r=await fetch(`${cfg.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:cfg.key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||'بيانات الدخول غير صحيحة');return d}
async function rpc(name){if(!await ensureSession())throw new Error('انتهت جلسة الإدارة. سجّل الدخول من جديد.');let r=await fetch(`${cfg.url}/rest/v1/rpc/${name}`,{method:'POST',headers:headers(),body:'{}'});if(r.status===401&&await refreshSession())r=await fetch(`${cfg.url}/rest/v1/rpc/${name}`,{method:'POST',headers:headers(),body:'{}'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||'تعذر تنفيذ العملية');return d}
async function checkAdmin(){try{if(!await ensureSession())return false;return !!(await rpc('is_admin'))}catch{return false}}
async function login(){try{msg('جارٍ تسجيل الدخول...');session=await auth($('email').value.trim(),$('password').value);if(!(await checkAdmin())){session=null;localStorage.removeItem(SESSION_KEY);throw new Error('هذا الحساب ليس مديراً. إذا كان أول حساب إدارة استعمل زر التفعيل.')}saveSession();showPanel();await loadAll()}catch(e){msg(e.message)}}
async function claim(){try{if(!session?.access_token){session=await auth($('email').value.trim(),$('password').value)}const ok=await rpc('claim_first_admin');if(!ok)throw new Error('يوجد مدير مفعّل مسبقاً. استخدم حساب المدير.');saveSession();showPanel();await loadAll()}catch(e){msg(e.message)}}
function showPanel(){$('loginBox').classList.add('hidden');$('panel').classList.remove('hidden')}
function logout(){localStorage.removeItem(SESSION_KEY);session=null;location.reload()}
async function api(path,opts={}){if(!await ensureSession())throw new Error('انتهت جلسة الإدارة. سجّل الدخول من جديد.');let r=await fetch(`${cfg.url}/rest/v1/${path}`,{...opts,headers:{...headers(),...(opts.headers||{})}});if(r.status===401&&await refreshSession())r=await fetch(`${cfg.url}/rest/v1/${path}`,{...opts,headers:{...headers(),...(opts.headers||{})}});if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.message||d.hint||'فشل الطلب')}return r.status===204?null:r.json()}
async function uploadFile(productId,file){if(!file)return null;if(file.size>100*1024*1024)throw new Error('الملف أكبر من 100MB. استعمل ملف ZIP مضغوط أصغر.');const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'_');const path=`products/${productId}/${Date.now()}_${safe}`;if(!await ensureSession())throw new Error('انتهت جلسة الإدارة. سجّل الدخول من جديد.');const send=async()=>fetch(`${cfg.url}/storage/v1/object/${BUCKET}/${path}`,{method:'POST',headers:{apikey:cfg.key,Authorization:`Bearer ${session.access_token}`,'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file});let r=await send();if(r.status===401&&await refreshSession())r=await send();if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.message||'فشل رفع ملف المنتج إلى Storage')}return path}
async function loadProducts(){products=await api('products?select=id,name,description,price_dzd,category,icon,file_key,file_name,download_limit,active,created_at&order=id');$('statProducts').textContent=products.length;renderProducts()}
async function loadOrders(){const rows=await api('orders?select=id,order_code,customer_name,customer_email,customer_phone,payment_method,status,total_dzd,payment_reference,paid_at,created_at&order=created_at.desc');$('statOrders').textContent=rows.length;$('ordersList').innerHTML=rows.length?rows.map(o=>`<div class="order"><div class="order-head"><strong>${escapeHtml(o.order_code)}</strong><span class="status ${o.status}">${escapeHtml(o.status)}</span></div><div>${escapeHtml(o.customer_name)} · ${escapeHtml(o.customer_phone)} · ${escapeHtml(o.customer_email)}</div><div class="muted">${new Date(o.created_at).toLocaleString('ar-DZ')} · ${money(o.total_dzd)}</div></div>`).join(''):'<div class="empty">لا توجد طلبات بعد.</div>'}
function renderProducts(){$('productList').innerHTML=products.length?products.map(p=>`<div class="admin-row"><div><strong>${p.icon} ${escapeHtml(p.name)}</strong><div class="muted">${money(p.price_dzd)} · ${escapeHtml(p.category)} · ${p.active?'ظاهر':'مخفي'} · ${p.file_key?'📁 ملف موجود':'⚠️ بدون ملف'}</div></div><div class="actions"><button onclick="editProduct(${p.id})">تعديل</button><button class="danger" onclick="removeProduct(${p.id})">حذف</button></div></div>`).join(''):'<div class="empty">لا توجد منتجات.</div>'}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$('editId').value=p.id;$('name').value=p.name;$('desc').value=p.description;$('price').value=p.price_dzd;$('cat').value=p.category;$('icon').value=p.icon;$('downloadLimit').value=p.download_limit||5;$('active').checked=!!p.active;$('productFile').value='';$('currentFile').textContent=p.file_key?`الملف الحالي: ${p.file_name||p.file_key}`:'لا يوجد ملف مرفوع';$('formTitle').textContent='تعديل المنتج';window.scrollTo({top:0,behavior:'smooth'})}
async function saveProduct(e){e.preventDefault();const btn=e.submitter;try{btn.disabled=true;const id=$('editId').value;const file=$('productFile').files[0]||null;const body={name:$('name').value.trim(),description:$('desc').value.trim(),price_dzd:Number($('price').value),category:$('cat').value,icon:($('icon').value||'📦').trim(),download_limit:Number($('downloadLimit').value)||5,active:$('active').checked,updated_at:new Date().toISOString()};if(!body.name||!body.description||!Number.isFinite(body.price_dzd)||body.price_dzd<=0)throw new Error('أدخل اسم ووصف وسعر صحيح.');let productId=id?Number(id):null;if(id){await api(`products?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)})}else{const created=await api('products',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});if(!Array.isArray(created)||!created[0]?.id)throw new Error('تم إنشاء المنتج لكن تعذر الحصول على رقم المنتج. أعد المحاولة.');productId=Number(created[0].id)}if(file){const path=await uploadFile(productId,file);await api(`products?id=eq.${encodeURIComponent(productId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({file_key:path,file_name:file.name,updated_at:new Date().toISOString()})})}resetForm();await loadProducts();alert(file?'تم حفظ المنتج ورفع الملف بنجاح.':'تم حفظ المنتج بنجاح.')}catch(e){alert(e.message)}finally{btn.disabled=false}}
async function removeProduct(id){if(!confirm('هل تريد حذف هذا المنتج من قاعدة البيانات؟'))return;try{await api(`products?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'});await loadProducts()}catch(e){alert(e.message)}}
function resetForm(){$('productForm').reset();$('editId').value='';$('icon').value='📦';$('downloadLimit').value=5;$('active').checked=true;$('currentFile').textContent='';$('formTitle').textContent='إضافة منتج'}
async function loadAll(){await Promise.all([loadProducts(),loadOrders()])}
$('loginBtn').onclick=login;$('claimBtn').onclick=claim;$('logoutBtn').onclick=logout;$('productForm').onsubmit=saveProduct;$('cancelEdit').onclick=resetForm;
(async()=>{try{if(await checkAdmin()){showPanel();await loadAll()}}catch{localStorage.removeItem(SESSION_KEY);session=null}})();